### ISSUE TITLE
카테고리 필터링 API

### ISSUE THREAD

**Issue by seohyun-kim** [inu-appcenter/inu-events-server#19]
![image](https://user-images.githubusercontent.com/61939286/203318297-bef4694b-ecf2-4eb3-9c93-f1808938241b.png)

숫자로 갑시다.

**Comment by seohyun-kim** [comment]
진행 중인 행사만 내릴 건지 bool값 받아서 end_at 필터링 적용도 하기.

`where: {endAt: MoreThanOrEqual(new Date())}`

**Comment by seohyun-kim** [comment]
## TODO
1. 회원 비회원 여부에 따라 카테고리 별 목록 내려줄 때에도 차단한 유저 빼고 내려주기
2. 카테고리에도 페이징 적용하기.

**Comment by seohyun-kim** [comment]
https://github.com/inu-appcenter/inu-events-server/releases/tag/v0.4.13

카테고리 기존에 작성된 것은 0.4.13 버전에 적용됨.

**Comment by seokahi** [comment]
완료했습니당
