### ISSUE TITLE
필요 없어진 api 인지 확인 부탁드려용

### ISSUE THREAD

**Issue by HamBP** [inu-appcenter/inu-events-server#7]
![image](https://user-images.githubusercontent.com/35232655/155767745-91d02402-4f82-49b4-9cc7-d1c7af594b41.png)

카테고리별 알림이 아닌 새 글 알림이었을 때 사용하던 api 로 보이는데, 필요 없어진 api 라면 deprecated 이후 삭제하는 게 좋아보여요!

**Comment by potados99** [comment]
아님 이거 그거 마쟈여

`/subscription/subscribing`으로 구독 `여부`를 제어하구여, `/subscription/topics`로 구독 `대상`을 제어함니당 둘다 같이 써야 해요
